<RootWidget>:
    Screen1:

<IdeaLabel2@Label>:
    size_hint: .4, .3
    font_size: "100dp"
    font_name: "fonts/Montserrat-Bold.ttf" 
    color: (1, 1, 1, 1)

<Screen1>:
    canvas.before:
        PushMatrix:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            size: self.size
            pos: self.pos
    canvas.after:
        PopMatrix:
    FloatLayout:
        Button:
            background_down: ''
            background_normal: ''
            text: ''
            size_hint: None, None
            width: '25dp'
            height: '33dp'
            pos_hint: {'right': 0.12, 'top':0.98}
            #on_press: root.manager.current = "Screen3"
            Image:
                source: "images/arrow2.png"
                size: self.parent.size
                pos: self.parent.pos

        BoxLayout:
            orientation: "horizontal"
            size_hint: .5, .1
            pos_hint: {'center_x': 0.5, 'center_y': 0.88}
            padding: 0
            spacing: 0
            Label:
                color: (0, 14/255, 8/255, 1)
                id: to_idea
                text: ' [b]Log in to iDea[/b]'
                font_name: 'Arialbd'
                markup: True
                font_size: "20dp"
                pos_hint: {'x': 0.5}
                design_width: root.width/3
                canvas.before:
                    Color: 
                        rgba: (88/255, 195/255, 182/255, 1)
                    Rectangle:
                        size: 66, 10
                        pos: root.width/2 - 67, self.pos[1] + self.pos[1]/26
        BoxLayout:
            orientation: "vertical"
            size_hint: .5, .07
            pos_hint: {'center_x': 0.3, 'center_y': 0.81}
            Label:
                id: welcome_back
                text: "Welcome back! Sign in using your"
                font_name: "fonts/Montserrat-Light.ttf"
                font_size: "18dp"
                size_hint_x: None
                size: self.texture_size
                pos_hint: {'center_x': 0.9}
                color: (121/255, 124/255, 123/255, 1)
            Label:
                id: matric_no
                text: "matriculation number and password"
                font_name: "fonts/Montserrat-Light.ttf"
                font_size: "18dp"
                size_hint_x: None
                size: self.texture_size
                pos_hint: {'center_x': 0.9}
                color: (121/255, 124/255, 123/255, 1)
                        
        





<SmoothButton@Button>:
    background_color: (0, 0, 0, 0)          
    background_normal: ''
    background_down: ''
    back_color: (1, 1, 1, 1)
    border_radius: [15]
    canvas.before:
        Color:
            rgba: self.back_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: self.border_radius