<RootWidget>:
    Screen1:

<IdeaLabel2@Label>:
    size_hint: .4, .3
    font_size: "100dp"
    font_name: "fonts/Montserrat-Bold.ttf" 
    color: (1, 1, 1, 1)

<Screen1>:
    canvas.before:
        PushMatrix:
        Color:
            rgba: 0, 0, 0, 0
        Rectangle:
            size: self.size
            pos: self.pos
    canvas.after:
        PopMatrix:
    FloatLayout:
        IdeaLabel2:
            color: (1, 1, 1, 1) 
            id: idealabel2_complete
            text: "iDea"
            pos_hint: {'center_y':0.97, 'center_x': 0.5}
            font_size: "30dp"
        BoxLayout:
            orientation: 'vertical'
            size_hint: .5, .4
            pos_hint: {'center_x': 0.25, 'center_y': 0.725}
            Label:
                id: share
                text: "Share"
                font_name: "Arial"
                font_size: "80dp"
                size_hint_x: None
                size: self.texture_size
                pos_hint: {'left': 1}
            Label:
                id: information
                text: "Information"
                font_name: "Arial"
                font_size: "80dp"
                size_hint_x: None
                size: self.texture_size
                pos_hint: {'left':1}

            Label:
                id: easily
                text: "Easily"
                font_name: "Arial"
                font_size: "80dp"
                size_hint_x: None
                size: self.texture_size
                pos_hint: {'left':1}
            Label:
                id: within_mtu
                text: "Within MTU"
                font_name: "Arial"
                font_size: "80dp"
                size_hint_x: None
                size: self.texture_size
                pos_hint: {'left':1}